version: '3.9'
services:

  web-server:
    image: nginx:1.23.1-alpine
    container_name: tpe-web2-web-server
    ports:
      - ${NGNIX_PORT}:80
    depends_on:
      - php-server
    volumes:
      - ./app:/usr/share/nginx/html/app
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf

  php-server:
    build:
      context: ./php
      dockerfile: ./php.Dockerfile
    container_name: tpe-web2-php-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/usr/share/nginx/html/app
      - ./php/config/php.ini:/usr/local/etc/php/php.ini

  db:
    image: mysql:8.0.30
    container_name: tpe-web2-db
    ports: 
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'